const initialRows = [
    { 
     id: 1,
     sr: 1,
     bagPrepBy: ' ',
     employee: 'm admin',
     dept: 'filing',
     rmbagid:'0000008991',
     supplier: 'ashok01',
     item: 'METAL',
     type: 'GOLD',
     MType: '',
     quality: '14K',
     color: 'YELLOW',
     size: '',
     actualPcs: 0,
     actualUsed: 5.0,
     receive: 0.0,
     flag: 0 
    },
    { 
     id: 2,
     sr: 2,
     bagPrepBy: ' ',
     employee: 'm admin',
     dept: 'Setting',
     rmbagid:'0000008992',
     supplier: 'company',
     item: 'MISC',
     type: 'PRS',
     MType: '',
     quality: 'PD',
     color: 'PD',
     size: '2mm',
     actualPcs: 2,
     actualUsed: 2.0,
     receive: 0.0,
     flag: 2 
    },
    { 
     id: 3,
     sr: 3,
     bagPrepBy: ' ',
     employee: 'm admin',
     dept: 'filing',
     rmbagid:'0000008993',
     supplier: 'company',
     item: 'FINDING',
     type: 'GOLD',
     MType: '',
     quality: '22K',
     color: 'Yellow',
     size: '',
     actualPcs: 2,
     actualUsed: 2.0,
     receive: 0.0,
     flag: 1 
    },
    { 
     id: 4,
     sr: 4,
     bagPrepBy: ' ',
     employee: 'm admin',
     dept: 'filing',
     rmbagid:'0000008994',
     supplier: 'company',
     item: 'DIAMOND',
     type: 'ASSCH',
     MType: '',
     quality: 'flashy',
     color: 'blackgreen',
     size: 'Any',
     actualPcs: 2,
     actualUsed: 2.0,
     receive: 0.0,
     flag: 0 
    },
    { 
     id: 5,
     sr: 5,
     bagPrepBy: ' ',
     employee: 'm admin',
     dept: 'filing',
     rmbagid:'0000008995',
     supplier: 'company',
     item: 'COLOR STONE',
     type: 'CS-3-A',
     MType: '',
     quality: 'white coral',
     color: 'bluish',
     size: '1mm',
     actualPcs: 2,
     actualUsed: 2.0,
     receive: 0.0,
     flag: 0 
    },
    { 
      id: 6,
      sr: 6,
      bagPrepBy: ' ',
      employee: 'm admin',
      dept: 'filing',
      rmbagid:'0000008996',
      supplier: 'ashok01',
      item: 'METAL',
      type: 'GOLD',
      MType: '',
      quality: '14K',
      color: 'YELLOW',
      size: '',
      actualPcs: 0,
      actualUsed: 5.0,
      receive: 0.0,
      flag: 1 
     },
    
  ];
  export default initialRows;