import img from '../Assets/Jew.jpg';

export const dbJobdetails = [
    {
        jobId: "1/111111",
        designNumber: "FD4",
        serialFor: "WOMENS", 
        image: img,
        customerName: "ashok01",
        poNumber: "Test",
        location: "INDIA",
        currentStatus: "Filing-Issue",
        metal:'GOLD',
        metalpurity:'18K',
        metalcolor:'Yellow',
        diamond:1,
        diamondshape:'ROUND',
        diamondClarity:'vvs1',
        diamondcolor:'green',
        diamondsize:'1 mm',
        cs:1,
        csshape:'CUS',
        csClarity:'PD',
        cscolor:'rose gold',
        cssize:'3 mm',
        Misc:1,
        Miscshape:'MOTI',
        MiscClarity:'pure',
        Misccolor:'white',
        Miscsize:'Mix',
        metalwt:1.000,
        diamondwt:5.213,
        diamondpcs:2,
        cswt:4.617,
        cspcs:4,
        miscwt:8.223,
        miscpcs:1,
        SprewWt:20.000,
        lastReceived:10.480,
        losswt:0.89,
        maxloss:2,
        'Misc Add in Gross wt':'NO',
        'Is HMW Job?':'No',
        'AlloyWt':	'0.000',
        jobFlag: 'Issue',
        "isissue": 0
      },
    {
        jobId: "1/123456",
        designNumber: "FD4",
        serialFor: "WOMENS", 
        image: img,
        customerName: "ashok01"   ,
        poNumber: "Test",
        location: "INDIA",
        currentStatus: "Filing-Issue",
        metal:'GOLD',
        metalpurity:'14K',
        metalcolor:'Yellow',
        diamond:1,
        diamondshape:'ROUND',
        diamondClarity:'vvs1',
        diamondcolor:'green',
        diamondsize:'1 mm',
        cs:1,
        csshape:'CUS',
        csClarity:'PD',
        cscolor:'rose gold',
        cssize:'3 mm',
        Misc:1,
        Miscshape:'MOTI',
        MiscClarity:'pure',
        Misccolor:'white',
        Miscsize:'Mix',
        metalwt:1.000,
        diamondwt:5.213,
        diamondpcs:2,
        cswt:4.617,
        cspcs:4,
        miscwt:8.223,
        miscpcs:1,
        SprewWt:20.000,
        lastReceived:10.480,
        losswt:0.89,
        maxloss:2,
         'Misc Add in Gross wt':'NO',
         'Is HMW Job?':'No',
         'AlloyWt':	'0.000',
         "isissue": 1,
        jobFlag: 'Return',

      },
    {
        jobId: "1/222222",
        designNumber: "FD3",
        serialFor: "WOMENS", 
        image: img,
        customerName: "Guddu v patel",
        poNumber: "Test",
        location: "INDIA",
        currentStatus: "Filing-Issue",
        metal:'GOLD',
        metalpurity:'10K',
        metalcolor:'Yellow',
        diamond:1,
        diamondshape:'ROUND',
        diamondClarity:'vvs1',
        diamondcolor:'green',
        diamondsize:'1 mm',
        cs:1,
        csshape:'CUS',
        csClarity:'PD',
        cscolor:'rose gold',
        cssize:'3 mm',
        Misc:1,
        Miscshape:'MOTI',
        MiscClarity:'pure',
        Misccolor:'white',
        Miscsize:'Mix',
        metalwt:1.000,
        diamondwt:5.213,
        diamondpcs:2,
        cswt:4.617,
        cspcs:4,
        miscwt:8.223,
        miscpcs:1,
        SprewWt:20.000,
        lastReceived:10.480,
        losswt:0.89,
        maxloss:2,
         'Misc Add in Gross wt':'NO',
         'Is HMW Job?':'No',
         'AlloyWt':	'0.000',
         "isissue": 1,
         jobFlag: 'Issue',
      },
    {
        jobId: "1/333333",
        designNumber: "FD3",
        serialFor: "WOMENS", 
        image: img,
        customerName: "Guddu v patel",
        poNumber: "Test",
        location: "INDIA",
        currentStatus: "Filing-Issue",
        metal:'GOLD',
        metalpurity:'10K',
        metalcolor:'Yellow',
        diamond:1,
        diamondshape:'ROUND',
        diamondClarity:'vvs1',
        diamondcolor:'green',
        diamondsize:'1 mm',
        cs:1,
        csshape:'CUS',
        csClarity:'PD',
        cscolor:'rose gold',
        cssize:'3 mm',
        Misc:1,
        Miscshape:'MOTI',
        MiscClarity:'pure',
        Misccolor:'white',
        Miscsize:'Mix',
        metalwt:1.000,
        diamondwt:5.213,
        diamondpcs:2,
        cswt:4.617,
        cspcs:4,
        miscwt:8.223,
        miscpcs:1,
        SprewWt:20.000,
        lastReceived:10.480,
        losswt:0.89,
        maxloss:2,
         'Misc Add in Gross wt':'NO',
         'Is HMW Job?':'No',
         'AlloyWt':	'0.000',
         "isissue": 1,
         jobFlag: 'Issue',
      },
    {
        jobId: "1/444444",
        designNumber: "FD3",
        serialFor: "WOMENS", 
        image: img,
        customerName: "Guddu v patel",
        poNumber: "Test",
        location: "INDIA",
        currentStatus: "Filing-Issue",
        metal:'GOLD',
        metalpurity:'10K',
        metalcolor:'Yellow',
        diamond:1,
        diamondshape:'ROUND',
        diamondClarity:'vvs1',
        diamondcolor:'green',
        diamondsize:'1 mm',
        cs:1,
        csshape:'CUS',
        csClarity:'PD',
        cscolor:'rose gold',
        cssize:'3 mm',
        Misc:1,
        Miscshape:'MOTI',
        MiscClarity:'pure',
        Misccolor:'white',
        Miscsize:'Mix',
        metalwt:1.000,
        diamondwt:5.213,
        diamondpcs:2,
        cswt:4.617,
        cspcs:4,
        miscwt:8.223,
        miscpcs:1,
        SprewWt:20.000,
        lastReceived:10.480,
        losswt:0.89,
        maxloss:2,
         'Misc Add in Gross wt':'NO',
         'Is HMW Job?':'No',
         'AlloyWt':	'0.000',
         "isissue": 1,
         jobFlag: 'Issue',
      },
    {
        jobId: "1/555555",
        designNumber: "FD3",
        serialFor: "WOMENS", 
        image: img,
        customerName: "Guddu v patel",
        poNumber: "Test",
        location: "INDIA",
        currentStatus: "Filing-Issue",
        metal:'GOLD',
        metalpurity:'10K',
        metalcolor:'Yellow',
        diamond:1,
        diamondshape:'ROUND',
        diamondClarity:'vvs1',
        diamondcolor:'green',
        diamondsize:'1 mm',
        cs:1,
        csshape:'CUS',
        csClarity:'PD',
        cscolor:'rose gold',
        cssize:'3 mm',
        Misc:1,
        Miscshape:'MOTI',
        MiscClarity:'pure',
        Misccolor:'white',
        Miscsize:'Mix',
        metalwt:1.000,
        diamondwt:5.213,
        diamondpcs:2,
        cswt:4.617,
        cspcs:4,
        miscwt:8.223,
        miscpcs:1,
        SprewWt:20.000,
        lastReceived:10.480,
        losswt:0.89,
        maxloss:2,
         'Misc Add in Gross wt':'NO',
         'Is HMW Job?':'No',
         'AlloyWt':	'0.000',
         "isissue": 1,
         jobFlag: 'Issue',
      },
    {
        jobId: "1/666666",
        designNumber: "FD3",
        serialFor: "WOMENS", 
        image: img,
        customerName: "Guddu v patel",
        poNumber: "Test",
        location: "INDIA",
        currentStatus: "Filing-Issue",
        metal:'GOLD',
        metalpurity:'10K',
        metalcolor:'Yellow',
        diamond:1,
        diamondshape:'ROUND',
        diamondClarity:'vvs1',
        diamondcolor:'green',
        diamondsize:'1 mm',
        cs:1,
        csshape:'CUS',
        csClarity:'PD',
        cscolor:'rose gold',
        cssize:'3 mm',
        Misc:1,
        Miscshape:'MOTI',
        MiscClarity:'pure',
        Misccolor:'white',
        Miscsize:'Mix',
        metalwt:1.000,
        diamondwt:5.213,
        diamondpcs:2,
        cswt:4.617,
        cspcs:4,
        miscwt:8.223,
        miscpcs:1,
        SprewWt:20.000,
        lastReceived:10.480,
        losswt:0.89,
        maxloss:2,
         'Misc Add in Gross wt':'NO',
         'Is HMW Job?':'No',
         'AlloyWt':	'0.000',
         "isissue": 1,
         jobFlag: 'Issue',
      },
    {
        jobId: "1/777777",
        designNumber: "FD3",
        serialFor: "WOMENS", 
        image: img,
        customerName: "Guddu v patel",
        poNumber: "Test",
        location: "INDIA",
        currentStatus: "Filing-Issue",
        metal:'GOLD',
        metalpurity:'10K',
        metalcolor:'Yellow',
        diamond:1,
        diamondshape:'ROUND',
        diamondClarity:'vvs1',
        diamondcolor:'green',
        diamondsize:'1 mm',
        cs:1,
        csshape:'CUS',
        csClarity:'PD',
        cscolor:'rose gold',
        cssize:'3 mm',
        Misc:1,
        Miscshape:'MOTI',
        MiscClarity:'pure',
        Misccolor:'white',
        Miscsize:'Mix',
        metalwt:1.000,
        diamondwt:5.213,
        diamondpcs:2,
        cswt:4.617,
        cspcs:4,
        miscwt:8.223,
        miscpcs:1,
        SprewWt:20.000,
        lastReceived:10.480,
        losswt:0.89,
        maxloss:2,
         'Misc Add in Gross wt':'NO',
         'Is HMW Job?':'No',
         'AlloyWt':	'0.000',
         "isissue": 1,
         jobFlag: 'Issue',
      },
]