export const ReturnRmBags = [
    {
    rmbagid: "0000008991",
    Material: "METAL",
    Type: "GOLD",
    Color: "YELLOW",
    Purity: "14K",
    wt: 16.912,
    Location:'INDIA',
    customerName: "ashok01",
    Pcs:'',
    Shape:'',
    Clarity:'',
    Size:'',
},
    {
    rmbagid: "0000089911",
    Material: "METAL",
    Type: "GOLD",
    Color: "YELLOW",
    Purity: "14K",
    wt: 16.912,
    Location:'INDIA',
    customerName: "ashok01",
    Pcs:'',
    Shape:'',
    Clarity:'',
    Size:'',
},
    {
    rmbagid: "0000089912",
    Material: "METAL",
    Type: "GOLD",
    Color: "YELLOW",
    Purity: "12K",
    wt: 16.912,
    Location:'INDIA',
    customerName: "ashok01",
    Pcs:'',
    Shape:'',
    Clarity:'',
    Size:'',
},
    {
    rmbagid: "1000008993",
    Material: "METAL",
    Type: "GOLD",
    Color: "YELLOW",
    Purity: "14K",
    wt: 16.912,
    Location:'INDIA',
    customerName: "company",
    Pcs:'',
    Shape:'',
    Clarity:'',
    Size:'',
},

{
    rmbagid: "0000008992",
    Material: "MISC",
    Type: "MISC",
    Color: "PD",
    Purity: "",
    wt: 16.912,
    Location:'INDIA',
    customerName: "company",
    Pcs:'3',
    Shape:'PRS',
    Clarity:'PD',
    Size:'2mm',
},
{
    rmbagid: "0000089921",
    Material: "MISC",
    Type: "MISC",
    Color: "PD",
    Purity: "",
    wt: 16.912,
    Location:'INDIA',
    customerName: "company",
    Pcs:'3',
    Shape:'PRS',
    Clarity:'PD',
    Size:'2mm',
},
{
    rmbagid: "0000089922",
    Material: "MISC",
    Type: "MISC",
    Color: "PD",
    Purity: "",
    wt: 16.912,
    Location:'INDIA',
    customerName: "ashok01",
    Pcs:'3',
    Shape:'PRS',
    Clarity:'PD',
    Size:'2mm',
},
{
    rmbagid: "0000089923",
    Material: "MISC",
    Type: "MISC",
    Color: "PD",
    Purity: "",
    wt: 16.912,
    Location:'INDIA',
    customerName: "company",
    Pcs:'3',
    Shape:'RND',
    Clarity:'PD',
    Size:'2mm',
},
{
    rmbagid: "0000089931",
    Material: "FINDING",
    Type: "GOLD",
    Color: "Yellow",
    Purity: "22K",
    wt: 16.912,
    Location:'INDIA',
    customerName: "company",
    Pcs:'3',
    Shape:'',
    Clarity:'',
    Size:'',
},
{
    rmbagid: "0000089932",
    Material: "FINDING",
    Type: "GOLD",
    Color: "Yellow",
    Purity: "22K",
    wt: 16.912,
    Location:'INDIA',
    customerName: "ashok01",
    Pcs:'3',
    Shape:'',
    Clarity:'',
    Size:'',
},
{
    rmbagid: "0000089933",
    Material: "FINDING",
    Type: "GOLD",
    Color: "Yellow",
    Purity: "18K",
    wt: 16.912,
    Location:'INDIA',
    customerName: "company",
    Pcs:'3',
    Shape:'',
    Clarity:'',
    Size:'',
},
{
    rmbagid: "0000008994",
    Material: "DIAMOND",
    Type: "DIAMOND",
    Color: "blackgreen",
    Purity: "20K",
    wt: 16.912,
    Location:'Maharashtra',
    customerName: "company",
    Pcs:'3',
    Shape:'ASSCH',
    Clarity:'flashy',
    Size:'Any',
},
{
    rmbagid: "0000089941",
    Material: "DIAMOND",
    Type: "DIAMOND",
    Color: "blackgreen",
    Purity: "20K",
    wt: 16.912,
    Location:'Maharashtra',
    customerName: "company",
    Pcs:'3',
    Shape:'ASSCH',
    Clarity:'flashy',
    Size:'Any',
},
{
    rmbagid: "0000089942",
    Material: "DIAMOND",
    Type: "DIAMOND",
    Color: "blackgreen",
    Purity: "20K",
    wt: 16.912,
    Location:'Maharashtra',
    customerName: "ashok01",
    Pcs:'3',
    Shape:'ASSCH',
    Clarity:'flashy',
    Size:'Any',
},
{
    rmbagid: "0000089943",
    Material: "DIAMOND",
    Type: "DIAMOND",
    Color: "blackgreen",
    Purity: "20K",
    wt: 16.912,
    Location:'Maharashtra',
    customerName: "company",
    Pcs:'3',
    Shape:'ASSCH',
    Clarity:'vvs1',
    Size:'Any',
},
{
    rmbagid: "0000008995",
    Material: "COLOR STONE",
    Type: "COLOR STONE",
    Color: "bluish",
    Purity: "",
    wt: 23.345,
    Location:'INDIA',
    customerName: "company",
    Pcs:'3',
    Shape:'CS-3-A',
    Clarity:'white coral',
    Size:'1mm',
},
{
    rmbagid: "0000089951",
    Material: "COLOR STONE",
    Type: "COLOR STONE",
    Color: "bluish",
    Purity: "",
    wt: 23.345,
    Location:'INDIA',
    customerName: "company",
    Pcs:'3',
    Shape:'CS-3-A',
    Clarity:'white coral',
    Size:'1mm',
},
{
    rmbagid: "0000089952",
    Material: "COLOR STONE",
    Type: "COLOR STONE",
    Color: "bluish",
    Purity: "",
    wt: 23.345,
    Location:'INDIA',
    customerName: "ashok01",
    Pcs:'3',
    Shape:'CS-3-A',
    Clarity:'white coral',
    Size:'1mm',
},
{
    rmbagid: "0000089953",
    Material: "COLOR STONE",
    Type: "COLOR STONE",
    Color: "bluish",
    Purity: "",
    wt: 23.345,
    Location:'INDIA',
    customerName: "company",
    Pcs:'3',
    Shape:'CS-3-A',
    Clarity:'white coral',
    Size:'2mm',
},
{
    rmbagid: "0000008996",
    Material: "DIAMOND",
    Type: "DIAMOND",
    Color: "A3",
    Purity: "",
    wt: 23.345,
    Location:'INDIA',
    customerName: "ashok01",
    Pcs:'3',
    Shape:'RND',
    Clarity:'vvs1',
    Size:'1mm',

},
{
    rmbagid: "0000008997",
    Material: "DIAMOND",
    Type: "DIAMOND",
    Color: "A3",
    Purity: "",
    wt: 23.345,
    Location:'INDIA',
    customerName: "Guddu v patel",
    Pcs:'3',
    Shape:'RND',
    Clarity:'vvs1',
    Size:'1mm',

},
{
    rmbagid: "0000008998",
    Material: "COLOR STONE",
    Type: "COLOR STONE",
    Color: "BLK",
    Purity: "",
    wt: 23.345,
    Location:'INDIA',
    customerName: "Guddu v patel",
    Pcs:'3',
    Shape:'CUS',
    Clarity:'CER',
    Size:'1mm',

},
{
    rmbagid: "0000008999",
    Material: "COLOR STONE",
    Type: "",
    Color: "BLK",
    Purity: "",
    wt: 23.345,
    Location:'INDIA',
    customerName: "company",
    Pcs:'3',
    Shape:'CUS',
    Clarity:'CER',
    Size:'1mm',

},
{
    rmbagid: "0000009000",
    Material: "COLOR STONE",
    Type: "",
    Color: "REDS",
    Purity: "",
    wt: 23.345,
    Location:'INDIA',
    customerName: "ashok01",
    Pcs:'3',
    Shape:'CUS',
    Clarity:'CD',
    Size:'2mm',
},

]