export const Rmbag = [
        {
        rfbagid: "0000008991",
        Material: "METAL",
        Mtype: 'NATURAL',
        Type: "GOLD",
        Color: "YELLOW",
        Purity: "14K",
        wt: 16.912,
         beforewt:99.12,
        Location:'INDIA',
        customerName: "ashok01",
        Shape:'',
        Clarity:'',
        Size:'',

},
{
        rfbagid: "0000008992",
        Material: "METAL",
        Mtype: 'NATURAL',
        Type: "GOLD",
        Color: "YELLOW",
        Purity: "18K",
        wt: 16.912,
        beforewt:99.12,
        Location:'INDIA',
        customerName: "ashok02",
        Shape:'',
        Clarity:'',
        Size:'',
},
{
        rfbagid: "0000008993",
        Material: "METAL",
        Mtype: 'NATURAL',
        Type: "GOLD",
        Color: "YELLOW",
        Purity: "20K",
        wt: 16.912,
        beforewt:99.12,
        Location:'INDIA',
        customerName: "stock",
        Shape:'',
        Clarity:'',
        Size:'',
},
{
        rfbagid: "0000008994",
        Material: "METAL",
        Mtype: 'NATURAL',
        Type: "GOLD",
        Color: "YELLOW",
        Purity: "20K",
        wt: 16.912,
        beforewt:99.12,
        Location:'Maharashtra',
        customerName: "stock",
        Shape:'',
        Clarity:'',
        Size:'',
},
{
        rfbagid: "0000008995",
        Material: "DIAMOND",
        Mtype: '',
        Type: "",
        Color: "A3",
        Purity: "",
        wt: 23.345,
        beforewt:99.12,
        Location:'INDIA',
        customerName: "stock",
        Shape:'RND',
        Clarity:'vvs1',
        Size:'1mm',
},
{
        rfbagid: "0000008996",
        Material: "DIAMOND",
        Mtype: 'NATURAL',
        Type: "",
        Color: "A3",
        Purity: "",
        wt: 23.345,
        beforewt:99.12,
        Location:'INDIA',
        customerName: "ashok01",
        Shape:'RND',
        Clarity:'vvs1',
        Size:'1mm',

},
{
        rfbagid: "0000008997",
        Material: "DIAMOND",
        Mtype: '',
        Type: "",
        Color: "A3",
        Purity: "",
        wt: 23.345,
        beforewt:99.12,
        Location:'INDIA',
        customerName: "Guddu v patel",
        Shape:'RND',
        Clarity:'vvs1',
        Size:'1mm',

},
{
        rfbagid: "0000008998",
        Material: "COLOR STONE",
        Mtype: 'NATURAL',
        Type: "",
        Color: "BLK",
        Purity: "",
        wt: 23.345,
        beforewt:99.12,
        Location:'INDIA',
        customerName: "Guddu v patel",
        Shape:'CUS',
        Clarity:'CER',
        Size:'1mm',

},
{
        rfbagid: "0000008999",
        Material: "COLOR STONE",
        Mtype: 'NATURAL',
        Type: "",
        Color: "BLK",
        Purity: "",
        wt: 23.345,
        beforewt:99.12,
        Location:'INDIA',
        customerName: "stock",
        Shape:'CUS',
        Clarity:'CER',
        Size:'1mm',

},
{
        rfbagid: "0000009000",
        Material: "COLOR STONE",
        Mtype: '',
        Type: "",
        Color: "REDS",
        Purity: "",
        wt: 23.345,
        beforewt:99.12,
        Location:'INDIA',
        customerName: "ashok01",
        Shape:'CUS',
        Clarity:'CD',
        Size:'2mm',
},

]