export const Rmbag = [
        {
        rfbagid: "0000008991",
        Material: "METAL",
        Type: "GOLD",
        Color: "YELLOW",
        Purity: "14K",
        wt: "16.912/16.912",
        Location:'Gujarat',
        customerName: "ashok01",
        shape:'',
        Clarity:'',
        size:'',

},
{
        rfbagid: "0000008992",
        Material: "METAL",
        Type: "GOLD",
        Color: "YELLOW",
        Purity: "18K",
        wt: "16.912/16.912",
        Location:'Gujarat',
        customerName: "ashok02",
        shape:'',
        Clarity:'',
        size:'',


},
{
        rfbagid: "0000008993",
        Material: "METAL",
        Type: "GOLD",
        Color: "YELLOW",
        Purity: "20K",
        wt: "16.912/16.912",
        Location:'Gujarat',
        customerName: "stock",
        shape:'',
        Clarity:'',
        size:'',
},
{
        rfbagid: "0000008994",
        Material: "METAL",
        Type: "GOLD",
        Color: "YELLOW",
        Purity: "20K",
        wt: "16.912/16.912",
        Location:'Maharashtra',
        customerName: "stock",
        shape:'',
        Clarity:'',
        size:'',
},
{
        rfbagid: "0000008995",
        Material: "DIAMOND",
        Type: "",
        Color: "A3",
        Purity: "",
        wt: 23.345,
        Location:'Gujarat',
        customerName: "stock",
        shape:'RND',
        Clarity:'vvs1',
        size:'1mm',
},
{
        rfbagid: "0000008996",
        Material: "DIAMOND",
        Type: "",
        Color: "A3",
        Purity: "",
        wt: 23.345,
        Location:'Gujarat',
        customerName: "ashok01",
        shape:'RND',
        Clarity:'vvs1',
        size:'1mm',

},
{
        rfbagid: "0000008997",
        Material: "DIAMOND",
        Type: "",
        Color: "A3",
        Purity: "",
        wt: 23.345,
        Location:'Gujarat',
        customerName: "Guddu v patel",
        shape:'RND',
        Clarity:'vvs1',
        size:'1mm',

},
{
        rfbagid: "0000008998",
        Material: "COLOR STONE",
        Type: "",
        Color: "BLK",
        Purity: "",
        wt: 23.345,
        Location:'Gujarat',
        customerName: "Guddu v patel",
        shape:'CUS',
        Clarity:'CER',
        size:'1mm',

},
{
        rfbagid: "0000008998",
        Material: "COLOR STONE",
        Type: "",
        Color: "BLK",
        Purity: "",
        wt: 23.345,
        Location:'Gujarat',
        customerName: "stock",
        shape:'CUS',
        Clarity:'CER',
        size:'1mm',

},
{
        rfbagid: "0000008998",
        Material: "COLOR STONE",
        Type: "",
        Color: "REDS",
        Purity: "",
        wt: 23.345,
        Location:'Gujarat',
        customerName: "ashok01",
        shape:'CUS',
        Clarity:'CD',
        size:'2mm',

},

]